"""signalement des questions de quiz par les etudiants

Revision ID: 10953af73738
Revises: 5aff8ea85a7d
Create Date: 2026-08-03 11:28:09.468011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10953af73738'
down_revision: Union[str, None] = '5aff8ea85a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signalementquestionquiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tentative_id', sa.Integer(), nullable=False),
    sa.Column('index_question', sa.Integer(), nullable=False),
    sa.Column('signale_par_id', sa.Integer(), nullable=False),
    sa.Column('motif', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_signalement', sa.DateTime(), nullable=False),
    sa.Column('traite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['signale_par_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['tentative_id'], ['tentativequiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signalementquestionquiz')
    # ### end Alembic commands ###
