"""salon enrichi (pieces jointes, suppression, signalement) et bannissement utilisateur

Revision ID: 5aff8ea85a7d
Revises: 9a2647a792c7
Create Date: 2026-08-02 07:37:28.223136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5aff8ea85a7d'
down_revision: Union[str, None] = '9a2647a792c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signalementmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('signale_par_id', sa.Integer(), nullable=False),
    sa.Column('motif', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_signalement', sa.DateTime(), nullable=False),
    sa.Column('traite', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messagecercle.id'], ),
    sa.ForeignKeyConstraint(['signale_par_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messagecercle', sa.Column('piece_jointe_chemin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('messagecercle', sa.Column('piece_jointe_nom', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # server_default indispensable ici : sans ca, ajouter une colonne
    # NOT NULL a une table qui contient deja des lignes (le cas en
    # production) echoue, faute de valeur a donner aux lignes existantes.
    op.add_column('messagecercle', sa.Column('supprime', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('utilisateur', sa.Column('banni', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'banni')
    op.drop_column('messagecercle', 'supprime')
    op.drop_column('messagecercle', 'piece_jointe_nom')
    op.drop_column('messagecercle', 'piece_jointe_chemin')
    op.drop_table('signalementmessage')
    # ### end Alembic commands ###
