"""theme du jour unique avec cercle dedie

Revision ID: 6ce046f6408e
Revises: 90985df0059b
Create Date: 2026-08-08 02:28:51.625483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ce046f6408e'
down_revision: Union[str, None] = '90985df0059b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themedujour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_jour', sa.Date(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amorce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cercle_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cercle_id'], ['cercleetude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themedujour_date_jour'), 'themedujour', ['date_jour'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themedujour_date_jour'), table_name='themedujour')
    op.drop_table('themedujour')
    # ### end Alembic commands ###
