"""baseline schema existant

Revision ID: 70e569fdc4ba
Revises: 
Create Date: 2026-07-29 22:33:37.748244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70e569fdc4ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculte_nom'), 'faculte', ['nom'], unique=True)
    op.create_table('filiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faculte_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculte_id'], ['faculte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mot_de_passe_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ETUDIANT', 'SPONSOR', 'ADMIN', name='roleutilisateur'), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_telephone'), 'utilisateur', ['telephone'], unique=True)
    op.create_table('abonnement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('prix_ariary', sa.Integer(), nullable=False),
    sa.Column('fournisseur_paiement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_paiement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE_PAIEMENT', 'ACTIF', 'EXPIRE', name='statutabonnement'), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cercleetude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('createur_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('titre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matiere', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_document', sa.Enum('ANNALE', 'CORRIGE', 'FICHE', 'COURS', name='typedocument'), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('chemin_fichier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'APPROUVE', 'REJETE', name='statutdocument'), nullable=False),
    sa.Column('nb_telechargements', sa.Integer(), nullable=False),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filiere.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_reference'), 'document', ['reference'], unique=True)
    op.create_table('membrecercle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cercle_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('date_adhesion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cercle_id'], ['cercleetude.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messagecercle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cercle_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('contenu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['cercle_id'], ['cercleetude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messagecercle')
    op.drop_table('membrecercle')
    op.drop_index(op.f('ix_document_reference'), table_name='document')
    op.drop_table('document')
    op.drop_table('cercleetude')
    op.drop_table('abonnement')
    op.drop_index(op.f('ix_utilisateur_telephone'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('filiere')
    op.drop_index(op.f('ix_faculte_nom'), table_name='faculte')
    op.drop_table('faculte')
    # ### end Alembic commands ###
