"""tuteur IA et mode examen chronometre

Revision ID: 90985df0059b
Revises: 10953af73738
Create Date: 2026-08-05 03:08:00.505447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90985df0059b'
down_revision: Union[str, None] = '10953af73738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessiontuteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explication', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exemple', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tentativequiz', sa.Column('mode_examen', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tentativequiz', sa.Column('duree_secondes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tentativequiz', 'duree_secondes')
    op.drop_column('tentativequiz', 'mode_examen')
    op.drop_table('sessiontuteur')
    # ### end Alembic commands ###
