"""ajout tentative quiz pour quiz IA par theme

Revision ID: 9a2647a792c7
Revises: 6b82c7c74c92
Create Date: 2026-07-31 02:14:08.507565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a2647a792c7'
down_revision: Union[str, None] = '6b82c7c74c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativequiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('matiere', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('niveau', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulte', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nb_questions', sa.Integer(), nullable=False),
    sa.Column('questions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reponses_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tentativequiz')
    # ### end Alembic commands ###
