"""ajout abonnement etudiant essai gratuit

Revision ID: d2fd44e37bc9
Revises: 70e569fdc4ba
Create Date: 2026-07-29 22:33:45.057744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2fd44e37bc9'
down_revision: Union[str, None] = '70e569fdc4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnementetudiant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('ESSAI', 'EN_ATTENTE', 'ACTIF', 'EXPIRE', 'REFUSE', name='statutabonnementetudiant'), nullable=False),
    sa.Column('date_debut_essai', sa.DateTime(), nullable=False),
    sa.Column('date_fin_essai', sa.DateTime(), nullable=False),
    sa.Column('date_fin_abonnement', sa.DateTime(), nullable=True),
    sa.Column('preuve_paiement_chemin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fournisseur_paiement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_paiement', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valide_par_admin_id', sa.Integer(), nullable=True),
    sa.Column('date_derniere_action_admin', sa.DateTime(), nullable=True),
    sa.Column('motif_refus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_maj', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.ForeignKeyConstraint(['valide_par_admin_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abonnementetudiant')
    # ### end Alembic commands ###
